# -*- coding: utf-8 -*-

eng = {
    "file": "&File",
    "new": "New",
    "new project general desc": "<p>Set Width/ Height/ Background of your new Image</p>"
                                "<p>size[64 = default; min. = 1]</p>",
    "new project width desc": "<p>Width</p>"
                              "<p>[64 = default; min. = 1]</p>",
    "new project height desc": "<p>Height</p>"
                               "<p>[64 = default; min. = 1]</p>",
    "new project background desc": "<p>Fill the Background with:</p>"
                                   "Transparency / Color1",
    "set width": "set Width ",
    "set height": "set Height",
    "background": "Background",
    "transparency": "Transparency",
    "color1": "Color1",
    "open": "Open",
    "open image": "Open Image",
    "image too big text": "The Image you are trying to open\nis too big.",
    "save": "Save",
    "save image": "Save Image",
    "quick save": "Quicksave",
    "exit": "Exit",
    "settings": "&Settings",
    "settings title": "Settings",
    "general settings": "General Settings",
    "misc": "Miscellaneous",
    "language": "Language",
    "english": "English",
    "german": "German",
    "fill only connected pixels": "   fill only connected pixels",
    "visualize fill algorithm": "   visualize Fill Algorithm",
    "need to restart": "You have to restart the application\nfor the changes to take effect.",
    "paintwindow settings": "PaintWindow Settings",
    "fill tool settings": "Fill Tool Settings",
    "fill tool tolerance": "Fill Tolerance",
    "tolerance": "Tolerance in %",
    "imageload settings": "Image Load Settings",
    "enable maxsize": "   Image-Maxsize",
    "image maxsize warning": "Disabling ImageMaxsize\ncan result in performance issues and crashes.",
    "help": "&Help",
    "get help": "open in Browser",
    "tools": "Tools",
    "draw": "Draw",
    "draw transparency": "Draw Transparency",
    "fill": "Fill",
    "fill transparency": "Fill with Transparency",
    "erase": "Erase",
    "undo": "undo",
    "redo": "redo",
    "draw thickness": "Draw Thickness",
    "color palette": "Color Palette",
    "color2": "Color2",
    "color3": "Color3",
    "color4": "Color4",
    "color5": "Color5",
    "color6": "Color6",
    "color7": "Color7",
    "color8": "Color8",
    "color9": "Color9",
    "color10": "Color10",
    "color11": "Color11",
    "color12": "Color12",
    "color13": "Color13",
    "color14": "Color14",
    "color15": "Color15",
    "color16": "Color16",
    "cancel": "Cancel",
    "close": "Close",
    "save as": "Save as",
    "save as grayscale image": "   Save as Grayscale Image",
    "advanced settings": "Advanced Settings",
    "close warning": "Unsaved changes are lost!",
    "close image": "Close Image",
    "image load error text": "An Error occurred \nwhile loading the image.",
    "image format error text": "The format of the image is not supported.",
    "non ascii error": "The file-path contains \nnon ASCII characters (ä/ö/ü/ß...).",
    "untitled": "untitled",
    "save enlarged": "Save enlarged",
    "size": "Size:",
    "100% size":   "     100%",
    "400% size":   "    400%",
    "900% size":   "    900%",
    "1600% size":  "  1600%",
    "2500% size":  "  2500%",
    "3600% size":  "  3600%",
    "4900% size":  "  4900%",
    "6400% size":  "  6400%",
    "8100% size":  "  8100%",
    "10000% size": "10000%",
    "jpg (set quality)": "JPG [Quality]",
    "png (set compression)": "PNG [Compression]",
    "cant save image to this path": "PixelPaint is unable to save \nyour image to the current path.",
    "image save error": "An Error occurred while saving the image, \n"
                        "check if you have the permission \n"
                        "to save a file to that path."
}

ger = {
    "file": "&Datei",
    "new": "Neu",
    "new project general desc": "<p>Bestimmen Sie Höhe/ Breite/ Hintergrund Ihres neuen Bildes</p>"
                                "<p>Größe[64 = Standard; min. = 1]</p>",
    "new project width desc": "<p>Höhe</p>"
                              "<p>[64 = Standard; min. = 1]</p>",
    "new project height desc": "<p>Breite</p>"
                               "<p>[64 = Standard; min. = 1]</p>",
    "new project background desc": "<p>Fülle den Hintergrund mit:</p>"
                                   "Transparenz / Farbe1 (Hauptfarbe)",
    "set width": "Breite",
    "set height": "Höhe ",
    "background": "Hintergrund",
    "transparency": "Transparenz",
    "color1": "Farbe1",
    "open": "Öffnen",
    "open image": "Bild öffnen",
    "image too big text": "Das Bild, das Sie öffnen möchten, \nist zug roß.",
    "save": "Speichern",
    "save image": "Speichern",
    "quick save": "Schnellspeichern",
    "exit": "Schließen",
    "settings": "&Einstellungen",
    "settings title": "Einstellungen",
    "general settings": "Allgemeine Einstellungen",
    "misc": "Sonstiges",
    "language": "Sprache",
    "english": "Englisch",
    "german": "Deutsch",
    "fill only connected pixels": "   nur verbundene Pixel füllen",
    "visualize fill algorithm": "   Füll Algorithmus visualisieren",
    "need to restart": "Sie müssen das Programm neu starten,\ndamit die Änderungen wirksam werden.",
    "paintwindow settings": "Zeischenfenster Einstellungen",
    "fill tool settings": "Füll Werkzeug Einstellungen",
    "fill tool tolerance": "Füll Toleranz",
    "tolerance": "Toleranz in %",
    "imageload settings": "Bild Lade Einstellungen",
    "enable maxsize": "   Max. Bildgröße",
    "image maxsize warning": "Das Deaktivieren der maximalen Bildgröße \nkann zu Performanceproblemen und Abstürzen "
                             "führen.",
    "help": "&Hilfe",
    "get help": "öffnen im Browser",
    "tools": "Werkzeuge",
    "draw": "Zeichnen",
    "draw transparency": "Transparenz Zeichnen",
    "fill": "Ausfüllen",
    "fill transparency": "Ausfüllen mit Transparenz",
    "erase": "Radieren",
    "undo": "rückgängig",
    "redo": "wiederherstellen",
    "draw thickness": "Strich-Größe",
    "color palette": "Farb Palette",
    "color2": "Farbe2",
    "color3": "Farbe3",
    "color4": "Farbe4",
    "color5": "Farbe5",
    "color6": "Farbe6",
    "color7": "Farbe7",
    "color8": "Farbe8",
    "color9": "Farbe9",
    "color10": "Farbe10",
    "color11": "Farbe11",
    "color12": "Farbe12",
    "color13": "Farbe13",
    "color14": "Farbe14",
    "color15": "Farbe15",
    "color16": "Farbe16",
    "cancel": "Abbrechen",
    "close": "Schließen",
    "save as": "Speichern unter",
    "save as grayscale image": "   als Graustufen Bild speichern",
    "advanced settings": "Erweiterte Einstellungen",
    "close warning": "Nicht gespeicherte Daten \ngehen verloren!",
    "close image": "Bild Schließen",
    "image load error text": "Beim Laden des Bildes \nist ein Fehler aufgetreten.",
    "image format error text": "Das Bildformat wird nicht unterstützt.",
    "non ascii error": "Der Dateipfad beinhaltet \nnicht ASCII Buchstaben (ä/ö/ü/ß...).",
    "untitled": "unbenannt",
    "save enlarged": "vergrößert Speichern",
    "size": "Größe:",
    "100% size":   "     100%",
    "400% size":   "     400%",
    "900% size":   "    900%",
    "1600% size":  "  1600%",
    "2500% size":  "  2500%",
    "3600% size":  "  3600%",
    "4900% size":  "  4900%",
    "6400% size":  "  6400%",
    "8100% size":  "  8100%",
    "10000% size": "10000%",
    "jpg (set quality)": "JPG [Qualität]",
    "png (set compression)": "PNG [Kompressionsstärke]",
    "cant save image to this path": "PixelPaint kann Ihr Bild nicht \nunter dem angegebenen Pfad speichern.",
    "image save error": "Während dem Speichern des Bildes ist ein Fehler \n"
                        "aufgetreten, gehen Sie sicher, dass Sie die Berechtigung \n"
                        "haben, eine Datei unter diesem Pfad zu speichern."
}
