# -*- coding: utf-8 -*-
"""
Language: eng/ ger dictionary
"""


eng = {
    "file": "&File",
    "new": "New",
    "new project general desc": "<p>Set Width/ Height/ Background of your new Project</p>"
                                "<p>size[64 = default; min. = 1]</p>",
    "new project width desc": "<p>Set the Width of your new Project</p>"
                              "<p>[64 = default; min. = 1]</p>",
    "new project height desc": "<p>Set the Height of your new Project</p>"
                               "<p>[64 = default; min. = 1]</p>",
    "new project background desc": "<p>Fill the Background of your new Project with:</p>"
                                   "Transparency / Color1",
    "set width": "set Width ",
    "set height": "set Height",
    "background": "Background",
    "transparency": "Transparency",
    "color1": "Color1",
    "open": "Open",
    "open image": "Open Image",
    "image too big text": "The Image you are trying to open\nis too big.",
    "save": "Save",
    "save image": "Save Image",
    "save as": "Save as",
    "exit": "Exit",
    "settings": "&Settings",
    "settings title": "Settings",
    "general settings": "General Settings",
    "misc": "Miscellaneous",
    "language": "Language",
    "english": "English",
    "german": "German",
    "fill only connected pixels": "   fill only connected pixels",
    "visualize fill algorithm": "   visualize Fill Algorithm",
    "need to restart": "You have to restart the application\nfor the changes to take effect.",
    "paintwindow settings": "PaintWindow Settings",
    "fill tool settings": "Fill Tool Settings",
    "fill tool tolerance": "Fill Tolerance",
    "tolerance": "Tolerance in %",
    "imageload settings": "Image Load Settings",
    "enable maxsize": "   Image-Maxsize",
    "image maxsize warning": "Disabling ImageMaxsize\ncan result in performance issues and crashes.",
    "help": "&Help",
    "get help": "open in Browser",
    "tools": "Tools",
    "draw": "Draw",
    "draw transparency": "Draw Transparency",
    "fill": "Fill",
    "fill transparency": "Fill with Transparency",
    "erase": "Erase",
    "undo": "undo",
    "redo": "redo",
    "draw width": "Draw Width",
    "color palette": "Color Palette",
    "color1/ main color": "Color1/ Main Color",
    "color2": "Color2",
    "color3": "Color3",
    "color4": "Color4",
    "color5": "Color5",
    "color6": "Color6",
    "color7": "Color7",
    "color8": "Color8",
    "color9": "Color9",
    "color10": "Color10",
    "color11": "Color11",
    "color12": "Color12",
    "color13": "Color13",
    "color14": "Color14",
    "color15": "Color15",
    "color16": "Color16",
    "cancel": "Cancel",
    "close": "Close",
    "close warning": "Unsaved changes are lost!",
    "close image": "Close Image",
    "image load error text": "An Error occurred \nwhile loading the image.",
    "image format error text": "The format of the image is not supported.",
    "non ascii error": "The file-path contains \nnon ASCII characters (ä/ö/ü/ß...).",
    "untitled": "untitled"
}

ger = {
    "file": "&Datei",
    "new": "Neu",
    "new project general desc": "<p>Bestimme Höhe/ Breite/ Hintergrund deines neuen Bildes</p>"
                                "<p>Größe[64 = Standard; min. = 1]</p>",
    "new project width desc": "<p>Höhe deines neuen Bildes</p>"
                              "<p>[64 = Standard; min. = 1]</p>",
    "new project height desc": "<p>Breite deines neuen Bildes</p>"
                               "<p>[64 = Standard; min. = 1]</p>",
    "new project background desc": "<p>Fülle den Hintergrund deines Bildes mit:</p>"
                                   "Transparenz / Farbe1 (Hauptfarbe)",
    "set width": "Breite",
    "set height": "Höhe ",
    "background": "Hintergrund",
    "transparency": "Transparenz",
    "color1": "Farbe1",
    "open": "Öffnen",
    "open image": "Bild öffnen",
    "image too big text": "Das Bild, das Sie öffnen möchten,\nist zug roß.",
    "save": "Speichern",
    "save image": "Bild speichern",
    "save as": "Speichern unter",
    "exit": "Schließen",
    "settings": "&Einstellungen",
    "settings title": "Einstellungen",
    "general settings": "Allgemeine Einstellungen",
    "misc": "Sonstiges",
    "language": "Sprache",
    "english": "Englisch",
    "german": "Deutsch",
    "fill only connected pixels": "   nur verbundene Pixel füllen",
    "visualize fill algorithm": "   Füll Algorithmus visualisieren",
    "need to restart": "Sie müssen das Programm neu starten,\ndamit die Änderungen wirksam werden.",
    "paintwindow settings": "Zeischenfenster Einstellungen",
    "fill tool settings": "Füll Werkzeug Einstellungen",
    "fill tool tolerance": "Füll Toleranz",
    "tolerance": "Toleranz in %",
    "imageload settings": "Bild Lade Einstellungen",
    "enable maxsize": "   Max. Bildgröße",
    "image maxsize warning": "Das Deaktivieren der maximalen Bildgröße\nkann zu Performanceproblemen und Abstürzen führen.",
    "help": "&Hilfe",
    "get help": "öffnen im Browser",
    "tools": "Werkzeuge",
    "draw": "Zeichnen",
    "draw transparency": "Transparenz Zeichnen",
    "fill": "Ausfüllen",
    "fill transparency": "Ausfüllen mit Transparenz",
    "erase": "Radieren",
    "undo": "rückgängig",
    "redo": "wiederherstellen",
    "draw width": "Strich-Breite",
    "color palette": "Farb Palette",
    "color1/ main color": "Farbe1/ Haupt-Farbe",
    "color2": "Farbe2",
    "color3": "Farbe3",
    "color4": "Farbe4",
    "color5": "Farbe5",
    "color6": "Farbe6",
    "color7": "Farbe7",
    "color8": "Farbe8",
    "color9": "Farbe9",
    "color10": "Farbe10",
    "color11": "Farbe11",
    "color12": "Farbe12",
    "color13": "Farbe13",
    "color14": "Farbe14",
    "color15": "Farbe15",
    "color16": "Farbe16",
    "cancel": "Abbrechen",
    "close": "Schließen",
    "close warning": "Nicht gespeicherte Daten \ngehen verloren!",
    "close image": "Bild Schließen",
    "image load error text": "Beim Laden des Bildes \nist ein Fehler aufgetreten.",
    "image format error text": "Das Bildformat wird nicht unterstützt.",
    "non ascii error": "Der Dateipfad beinhaltet \nnicht ASCII Buchstaben (ä/ö/ü/ß...).",
    "untitled": "unbenannt"
}
